### ISSUE TITLE
line ends aren't handled correctly on non-UNIX platforms

### ISSUE THREAD

**Issue by edkelly303** [lue-bird/elm-review-documentation-code-snippet#3] opened 2024-06-05 11:47 UTC
Hello! I've been struggling a bit with some weird issues with snippet parsing. I think I have narrowed the main one down to this minimal example:

This works in .elm files:

```elm
{-|
blah

    1
    --> 1
    
    x = 
        1
    1
    --> 1
-}
```

But the same code doesn't seem to parse correctly in README files:

````
```elm
1
--> 1

x = 
    1
1
--> 1
``` 
````

The error reported is "I expected to find syntactically valid elm code here but something is off with the imports/declarations."

**Comment by lue-bird** [comment] 2024-06-05 21:42
I wasn't able to reproduce this exact issue (now committed as a test). I have a strong suspicion that there _is_ an actual parsing error in your readme code snippet and the declaration documentation comment is just _not considered a code snippet at all_ (probably due to extra starting line-break which usually gets removed by elm-format, will look into it).

**Comment by edkelly303** [comment] 2024-06-06 09:16
I'm so sorry - I've tried this again this morning and I can't reproduce it either. I was convinced yesterday that there was a problem with adding more declarations after a `-->`, but it now works fine. So I'm not sure why I was having issues - I'll do some more investigation, you're probably right that it was something to do with line-breaks or white space.

(The other issue #4 I can still reproduce this morning)

**Comment by edkelly303** [comment] 2024-06-06 09:52
Ah! I think I've got it! 

If the line ending sequence is LF, it works fine. But if it's CR LF (which I think is what Windows usually does by default?) then I get the error. 

I can reproduce in VS Code with the `Change End of Line Sequence` command:

CR LF -> broken

![image](https://github.com/lue-bird/elm-review-documentation-code-snippet/assets/12986896/0cb86206-36a3-455d-9080-010d961fae5e)

LF -> works fine

![image](https://github.com/lue-bird/elm-review-documentation-code-snippet/assets/12986896/4258a976-eff9-4d5e-bf18-42f99249b6ca)

This will teach me to never ever use my work Windows PC for coding...

**Comment by lue-bird** [comment] 2024-06-06 11:41
Do you think it's fair to close this and open this in elm-syntax? (in case this needs fixing)

**Comment by edkelly303** [comment] 2024-06-06 11:58
Yes that's fine, if the problem is in elm-syntax then that makes sense. I'm afraid I don't know enough about either elm-syntax or elm-review rules to be much help!

**Comment by lue-bird** [comment] 2024-06-07 09:11
Should be fixed in the new release.
I'm a bit annoyed at myself for using `Sring.split "\n"` instead of `String.lines` in various places in parsing (maybe because I thought they were equivalent?)

**Closed as completed by lue-bird** 2024-06-07 09:11 UTC
Labels: bug

**Comment by edkelly303** [comment] 2024-06-07 09:21
Nice work, thank you! TIL about String.lines too.
