### ISSUE TITLE
Unit snippet causes elm-review to hang

### ISSUE THREAD

**Issue by edkelly303** [lue-bird/elm-review-documentation-code-snippet#4] opened 2024-06-05 14:46 UTC
Putting this snippet in a README:

````
```elm
()
--> ()
```
````

Or this in an .elm file:

```elm
{-|
hang

    ()
    --> ()
-}
```

... seems to cause elm-review to hang forever. I've observed this on both Windows and Ubuntu.

**Comment by lue-bird** [comment] 2024-06-05 21:51
Is it literally just with unit and equal checks? Anyway, will investigate tomorrow, thanks for reporting.

Edit: in tests, I couldn't reproduce (committed). Now trying in real codebase.

**Comment by edkelly303** [comment] 2024-06-06 12:14
Ah, I was using `elm-review --rules Review.Documentation.CodeSnippet --fix-all-without-prompt`... 

If I change it to `elm-review --rules Review.Documentation.CodeSnippet --fix`, I get

```
Fixed 1 issue so far-- ELM-REVIEW ERROR ----------------- tests/DocumentationCodeSnippetTest.elm:1:1

Review.Documentation.CodeSnippet: documentation code snippet test can be added

1| module DocumentationCodeSnippetTest exposing (tests)
   ^^^^^^

Adding them will help verify that code blocks in your readme and module
documentation work correctly.

I think I can fix this. Here is my proposal:

 3| {-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
 4|
 4| -}
···
17|                 "code snippet 0"
18|                 [ Test.test "0" (\() -> () |> Expect.equal ()) ]
19|                 [ Test.test "0" (\() -> (()) |> Expect.equal ()) ]
19|             ]

? Do you wish to apply this fix? » (Y/n)
```

So I think what might be happening is that the rule is putting extra parens around the `()`, and then elm-format is removing them again, so it gets into a loop.

**Comment by lue-bird** [comment] 2024-06-06 12:28
ooh! That makes sense. A fix to avoid unnecessary parens is published now.

**Closed as completed** 2024-06-06 12:31 UTC
Labels: bug
